site_name: Data 200
site_description: Applied Statistical Analysis Course

nav:
  - Welcome: index.md
  # - Installation Guide: 
theme:
  name: material
  features:
    - header.autohide
    - announce.dismiss
    - navigation.footer
  code:
    highlighting: true
    light: default
    dark: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  # You can remove 'codehilite' if pymdownx.highlight covers your needs

extra:
  generator: false
      
copyright: Copyright &copy; 2025 - Aayush Raj Regmi
