site_name: Data 200
site_description: Applied Statistical Analysis Course

nav:
  - Welcome: index.md
  - Getting Started:
    - Installation Guide: lectures/InstallationGuide.md
  - Introduction:
    - Introduction: lectures/Introduction.md
    - Statistical Foundations: lectures/StatisticsFoundations.md
    - ML / AI / DS Concepts: lectures/MLConcepts.md
  - Applied Statistical Analysis:
    - Regression:
      - Linear Regression: lectures/LinearRegression.md
      - Parameter Estimation: lectures/ParameterEstimation.md
      - Bias, Variance & Regularization: lectures/Regularization.md
    - Anova:
      - ANOVA, ANCOVA & MANOVA: lectures/ANOVA.md
      - ANCOVA — The Tip Money Mystery: lectures/ANCOVA.md
    - GLM:
      - Generalized Linear Models: lectures/GLM.md
    - Classification:
      - Logistic Regression: lectures/Classification.md
    - Mixed Models:
      - Linear Mixed Models: lectures/LinearMixedModels.md
  - Time Series Analysis:
    - Time Series: lectures/TimeSeries.md
    - Time Series Models: lectures/TimeSeriesModels.md
theme:
  name: readthedocs
  features:
    - header.autohide
    - announce.dismiss
    - navigation.footer
  code:
    highlighting: true
    dark: material
    light: default
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
      toc_depth: 3
  - admonition
  - pymdownx.details
  # You can remove 'codehilite' if pymdownx.highlight covers your needs

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  generator: false
      
copyright: Copyright &copy; 2025 - Aayush Raj Regmi
